"""
Django settings for projeto1 project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path  # Importa Path para manipulação de caminhos de arquivos

# Define o diretório base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Configurações rápidas para desenvolvimento - não usar em produção!
# Chave secreta usada para criptografia interna do Django
SECRET_KEY = 'django-insecure-*5hyd1sg^z=mfekf-gxkl2rlgwtc^7)k%02!ji9s$$dn^n@&n_'

# Ativa o modo debug (mostra erros detalhados)
DEBUG = False

# Lista de hosts permitidos a acessar o projeto
ALLOWED_HOSTS = ['*']

# Definição das aplicações instaladas no projeto
INSTALLED_APPS = [
    'django.contrib.admin',           # Admin do Django
    'django.contrib.auth',            # Sistema de autenticação
    'django.contrib.contenttypes',    # Tipos de conteúdo (modelos)
    'django.contrib.sessions',        # Gerenciamento de sessões
    'django.contrib.messages',        # Mensagens entre views e templates
    'django.contrib.staticfiles',     # Gerenciamento de arquivos estáticos
    'core',                           # Sua aplicação principal
]

# Middlewares são camadas de processamento entre requisições e respostas
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Arquivo principal de rotas do projeto
ROOT_URLCONF = 'projeto1.urls'

# Configuração dos templates (HTML)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Backend padrão de templates
        'DIRS': ['templates'],  # Diretórios onde o Django procura templates
        'APP_DIRS': True,       # Procura templates nas pastas das apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Adiciona o objeto request ao contexto
                'django.contrib.auth.context_processors.auth', # Adiciona informações de autenticação
                'django.contrib.messages.context_processors.messages', # Adiciona mensagens
            ],
        },
    },
]

# Configuração do WSGI (interface entre servidor web e Django)
WSGI_APPLICATION = 'projeto1.wsgi.application'

# Configuração do banco de dados (SQLite por padrão)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',         # Usa SQLite
        'NAME': BASE_DIR / 'db.sqlite3',               # Caminho do arquivo do banco de dados
    }
}

# Validações de senha para usuários
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internacionalização
LANGUAGE_CODE = 'pt-br'  # Define o idioma padrão como português do Brasil

TIME_ZONE = 'UTC'        # Fuso horário padrão

USE_I18N = True          # Ativa a internacionalização

USE_TZ = True            # Usa timezones

import os
# Configuração de arquivos estáticos (CSS, JS, imagens)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  
# Tipo padrão de campo para chaves primárias em modelos
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = 'index'  # Redireciona para a página inicial após logout
